export default {


    UserG:require('../assets/images/UserG.png'),
    forgame:require('../assets/images/forgame.png'),
    Redcircle:require('../assets/images/Redcircle.png'),
    Dummy:require('../assets/images/Dummy.png'),
    Avatar:require('../assets/images/Avatar.png'),
    Avatar2:require('../assets/images/Avatar2.png'),
    Avatar3:require('../assets/images/Avatar3.png'),
    RedBlack:require('../assets/images/RedBlack.png'),
    PlayStation:require('../assets/images/PlayStation.png'),
    CallDuty:require('../assets/images/CallDuty.png'),
    ForzaHorizon:require('../assets/images/ForzaHorizon.png'),
    tick:require('../assets/images/tick.png'),
    Miles:require('../assets/images/Miles.png'),
    editpencil:require('../assets/images/editpencil.png'),
    delete:require('../assets/images/delete.png'),
    spiderman:require('../assets/images/spiderman.png'),
    OmarNoaman:require('../assets/images/OmarNoaman.png'),
    Callmen:require('../assets/images/Callmen.png'),
    delivery:require('../assets/images/delivery.png'),
    Profit:require('../assets/images/Profit.png'),
    Banklogo:require('../assets/images/Banklogo.png'),
    GTCO:require('../assets/images/GTCO.png'),
    freegames:require('../assets/images/freegames.png'),
    playstationnull:require('../assets/images/playstationnull.png'),
    FIFA2022:require('../assets/images/FIFA2022.png'),
    Grandtheft:require('../assets/images/Grandtheft.png'),
    Shadow:require('../assets/images/Shadow.png'),
    Abdullah:require('../assets/images/Abdullah.png'),
    Heart:require('../assets/images/Heart.png'),
    StarYe:require('../assets/images/StarYe.png'),
    PlayS:require('../assets/images/PlayS.png'),
    Djplay:require('../assets/images/Djplay.png'),
    Pclaptop:require('../assets/images/Pclaptop.png'),
    Nintento:require('../assets/images/Nintento.png'),
    Action:require('../assets/images/Action.png'),
    Sports:require('../assets/images/Sports.png'),
    Shooter:require('../assets/images/Shooter.png'),
    Stratengy:require('../assets/images/Stratengy.png'),
    Store:require('../assets/images/Store.png'),
    fifagame:require('../assets/images/fifagame.png'),
    Fifamen:require('../assets/images/Fifamen.png'),
    fifagroup:require('../assets/images/fifagroup.png'),
    Textframe:require('../assets/images/Textframe.png'),
    Plateformplay:require('../assets/images/Plateformplay.png'),
    spiderscreenshot1:require('../assets/images/spiderscreenshot1.png'),
    screenshot2:require('../assets/images/screenshot2.png'),
    screenshot3:require('../assets/images/screenshot3.png'),
    screenshot4:require('../assets/images/screenshot4.png'),
    summary:require('../assets/images/summary.png'),
    COD4:require('../assets/images/COD4.png'),
    army:require('../assets/images/army.png'),
    Joker:require('../assets/images/Joker.png'),
    iconpark:require('../assets/images/iconpark.png'),
    Chat:require('../assets/images/Chat.png'),
    carbon:require('../assets/images/carbon.png'),
    download :require('../assets/images/download.png'),
    OmarNoaman:require('../assets/images/OmarNoaman.png'),
    GroupGame:require('../assets/images/GroupGame.png'),
    iPhone15:require('../assets/images/iPhone15.png'),
    Contactimage:require('../assets/images/Contactimage.png'),
    Rest :require('../assets/images/Rest.png'),
    middle:require('../assets/images/middle.png'),
    Frame551:require('../assets/images/Frame551.png'),
    Frame512:require('../assets/images/Frame512.png'),
    GamersStore:require('../assets/images/GamersStore.png'),
    pic1:require('../assets/images/pic1.png'),
    pic2:require('../assets/images/pic2.png'),
    pic3:require('../assets/images/pic3.png'),
    storegame:require('../assets/images/storegame.png'),
    circle:require('../assets/images/circle.png'),
    Ronaldo:require('../assets/images/Ronaldo.png'),
    BattleRoyale:require('../assets/images/BattleRoyale.png'),
    Boxer:require('../assets/images/Boxer.png'),
    Adventure :require('../assets/images/Adventure.png'),
    Survival:require('../assets/images/Survival.png'),
    Cards:require('../assets/images/Cards.png'),
    Car:require('../assets/images/Car.png'),
    rightwhitblue:require('../assets/images/rightwhitblue.png'),
    Emptyimage:require('../assets/images/Emptyimage.png'),
    Locationcheck:require('../assets/images/Locationcheck.png'),
    

  
  
    




    
}